language: cpp
dist: bionic
sudo: required
osx_image: xcode11

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then sudo apt-get install -y cmake libfreetype6-dev libharfbuzz-dev libglew-dev libglfw3-dev libglm-dev libfontconfig1-dev; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew update; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then brew install freetype fontconfig glew glfw3 glm harfbuzz; fi

script:
  - cmake . -DCMAKE_BUILD_TYPE=Release -DYAML_CPP_BUILD_CONTRIB=OFF -DYAML_CPP_BUILD_TESTS=OFF -DYAML_CPP_BUILD_TOOLS=OFF -DYAML_CPP_INSTALL=OFF
  - make all
